# LoginStreaks
# Author: Munch42
#
#_      ____   _____ _____ _   _    _____ _______ _____  ______          _  __ _____
#| |    / __ \ / ____|_   _| \ | |  / ____|__   __|  __ \|  ____|   /\   | |/ // ____|
#| |   | |  | | |  __  | | |  \| | | (___    | |  | |__) | |__     /  \  | ' /| (___
#| |   | |  | | | |_ | | | | . ` |  \___ \   | |  |  _  /|  __|   / /\ \ |  <  \___ \
#| |___| |__| | |__| |_| |_| |\  |  ____) |  | |  | | \ \| |____ / ____ \| . \ ____) |
#|______\____/ \_____|_____|_| \_| |_____/   |_|  |_|  \_\______/_/    \_\_|\_\_____/
#
#
#____            __  __                  _    _  _ ___
#|  _ \       _  |  \/  |                | |  | || |__ \
#| |_) |_   _(_) | \  / |_   _ _ __   ___| |__| || |_ ) |
#|  _ <| | | |   | |\/| | | | | '_ \ / __| '_ \__   _/ /
#| |_) | |_| |_  | |  | | |_| | | | | (__| | | | | |/ /_
#|____/ \__, (_) |_|  |_|\__,_|_| |_|\___|_| |_| |_|____|
#      __/ |
#     |___/
#

# LoginStreaks Commands
# /streak. Views your current streak.
# /topstreaks. Views the top streaks.

# LoginStreaks Permissions
# /streak command
streakPerm: "loginstreaks.streak"
# /topstreaks command
streakLBPerm: "loginstreaks.streaklb"
# /loginstreak base command
loginstreakPerm: "loginstreaks.loginstreak"
# /loginstreak reload command
loginstreakReloadPerm: "loginstreaks.loginstreak.reload"
# /timeleft command
timeleftPerm: "loginstreaks.timeleft"

# Economy Features
# An economy plugin such as EssentialsX is required to use LoginStreaks' built in economy features.
# If you do not need these features and do not want to install an economy plugin, please set this to false otherwise, leave this as true.
economy: true

# LoginStreaks Login Settings
# The default streak system is the original streak counting method used by LoginStreaks which counts up a player's streak every time they login more than 24 hours after they first logged in but less than 48 hours.
# E.G. If player A logged in at 3pm on the 22nd, the earliest they could get their next streak day would be at 3pm on the 23rd but they would need to claim it before 3pm on the 24th or it would reset.
# The new system introduced in version 3.0.0 will count a player's streak if they login anytime the next day as long as it is before midnight (As that would be the next next day)
# E.G. If a player logged in at anytime on the 12th, they could login at between 12am and 12pm on the 13th to claim their streak. If it was anytime after that (I.E. the 14th) it would reset.
# If you leave this as true, the default system will be used. If this is set to false, the system introduced in update 3.0.0 will be used.
defaultStreakSystem: true

# LoginStreaks Login Rewards and Messages
# No Permissions Message this is shown when the player does not have permissions to use the command. Set to "" to disable.
noPermsMessage: "&4You do not have permission to use that command!"

# Streak Command Message. The message shown when a player types /streak.
# Use %days% as a placeholder for the amount of streak days.
# Use %player% as a placeholder for the player's name.
streakMessage: "&2%player% &2you have logged in for %days% days in a row. Login tomorrow to increase your streak."

# Permission rewards options
# Weight option, if this is set to true, players will receive the highest weighted permission they have.
# If it is set to true, additionally you must make sure that all permission rewards have the "weight" section with an integer number. Decimal numbers (floats) will cause an error
# If this is set to false, the player will receive all of the rewards for all of the permissions they have.
weights: false

# TopStreak Command Message. This will be the first message shown when a player types /topstreaks. ie. Set to "" to just send the standings.
# <Your Message Here>
# 1. <Player Name>: <Streak>
# 2. <Player Name>: <Streak>
streakTopMessage: "&2This server's top streaks are: "

# This will be the colour code combination to set all placeholders. ie.
# If this is set to "&c&l" the message 1. <Name>: <Streak> would become "&2 1. <Name>: <Streak>"
streakTopEntriesColourCode: "&2"

# Money Received Message. Set to "" to disable. This will be sent to a player when they receive money as a reward.
# Use %money% as a placeholder for the amount of money received it will be formatted as $<money>.
# Use %days% as a placeholder for the amount of days they logged in.
rewardMoneyMessage: "&2&lYou received %money% as a reward for logging in %days% days in a row!"

# Command Received Message. Set to "" to disable. This will be sent to a player when a command is run as a reward.
# Use %command% as a placeholder for the commandExplanation of the command run.
# Use %days% as a placeholder for the amount of days they logged in.
rewardCommandMessage: "&2&lA command was run which %command% because you logged in for %days% days in a row!"

# Item Received Message. Set to "" to disable. This will be sent to a player when they receive an Item as a reward.
# Use %item% as a placeholder for the type of item.
# Use %itemAmount% as a placeholder for the amount of items received.
# Use %days% as a placeholder for the amount of days they logged in.
rewardItemMessage: "&2&lYou received %itemAmount% %item% as a reward for logging in for %days% days!"

# Optional Dependency Options:
# PlaceholderAPI Options:
# This will be the colour code combination to set all placeholders. ie.
# If this is set to "&c&l" the message %loginstreak_top1% would be &c&l <Top 1 Message>.
placeholderColourCodes: "&c"

# This will be the message shown beside the number in the placeholder if there are not enough players for that rank. ie.
# %loginstreak_top9% with only 8 total players with ranks would be: 9. <Your Message Below>
blankRankPlaceholder: "---------"

# Format:
# rewards: DO NOT CHANGE THIS SETTING. This is the main node of the section.
#   dayNum: This is the amount of days needed to get this. For example, if you set this to 7 they will get this reward after logging in for 7 days in a row.
#     rewardType: This should be set to either MONEY or ITEM or COMMAND. Set to MONEY if you want to give Money, REQUIRES: Vault. Set to ITEM if you want to give an item and set to COMMAND to run a command.
#     reward: This should either 1. Be the amount of Money given if the type is money. 2. Be the item given in all caps ie. IRON_BLOCK. Use ; to separate multiple items to give ie. IRON_BLOCK ; COAL_ORE. Or 3. The Command to run in "", you can use %player% as the player name. Separate multiple commands with ; as with items.
#     commandExplanation: This should be set to null unless the rewardType is COMMAND. If it is, set this to what the command does. Leave blank if you do not need the %command% placeholder above.
#     commandScope: This should be set to null unless the rewardType is COMMAND. If so, you can set this to either PLAYER to run the command as the player, or CONSOLE to run as the console. Set this for each command in rewards. Separate each one with a ; ie. CONSOLE ; PLAYER.
#     rewardAmount: This should be set to 0 if the rewardType is COMMAND or MONEY. Otherwise, set this to the amount of items the player will receive for each item. Separate the amounts with a ; for each item ie. 5 ; 10.
#     reset: (Optional) This should be set to either true or false. You do not need this field for a day as if it is not included it will be false. Once a player reaches this day, their streak will be reset to 1 if it is true.

rewards:
  5:
    rewardType: ITEM
    reward: RED_WOOL;IRON_BLOCK
    commandExplanation: null
    commandScope: null
    rewardAmount: "15;5"
  6:
    rewardType: COMMAND
    reward: "say %player% has logged in for 6 days now!;say If you also log in for 6 days like me you will receive this message."
    commandExplanation: "announces that you have a 6 day streak"
    commandScope: CONSOLE;PLAYER
    rewardAmount: "0"
  7:
    rewardType: COMMAND
    reward: "say %player% has logged in for 7 days now!"
    commandExplanation: "announces that you have a 7 day streak"
    commandScope: CONSOLE
    rewardAmount: "0"
  8:
    rewardType: MONEY
    reward: 5000
    commandExplanation: null
    commandScope: null
    rewardAmount: "0"
  9:
    rewardType: ITEM
    reward: RED_WOOL
    commandExplanation: null
    commandScope: null
    rewardAmount: "32"
    reset: true

# Format:
# permissionRewards: DO NOT CHANGE THIS SETTING. This is the main node of the section.
#   permission: This is the permission node needed to redeem the rewards within this tree on the days specified. For example, if you set this to "vip;special" they would need the vip.special node. You must change the "." between node sections to a ; for this to work. vip.special would become vip;special
#     weight: This should be set to an integer number representing the priority of the reward. Only use this once per permission. The higher the number, the higher the reward priority. If one is a 2 and the other is a 3 a player with both perms will receive the 3 weighted reward if "weights" above is true.
#     dayNum: This is the amount of days needed to get this when they have the permission node. For example, if you set this to 7 they will get this reward after logging in for 7 days in a row.
#       rewardType: This should be set to either MONEY or ITEM or COMMAND. Set to MONEY if you want to give Money, REQUIRES: Vault and an Economy plugin. Set to ITEM if you want to give an item and set to COMMAND to run a command.
#       reward: This should either 1. Be the amount of Money given if the type is money. 2. Be the item given in all caps ie. IRON_BLOCK. Use ; to separate multiple items to give ie. IRON_BLOCK ; COAL_ORE. Or 3. The Command to run in "", you can use %player% as the player name. Separate multiple commands with ; as with items.
#       commandExplanation: This should be set to null unless the rewardType is COMMAND. If it is, set this to what the command does. Leave blank if you do not need the %command% placeholder above.
#       commandScope: This should be set to null unless the rewardType is COMMAND. If so, you can set this to either PLAYER to run the command as the player, or CONSOLE to run as the console. Set this for each command in rewards. Separate each one with a ; ie. CONSOLE ; PLAYER.
#       rewardAmount: This should be set to 0 if the rewardType is COMMAND or MONEY. Otherwise, set this to the amount of items the player will receive for each item. Separate the amounts with a ; for each item ie. 5 ; 10.
#       reset: (Optional) This should be set to either true or false. You do not need this field for a day as if it is not included it will be false. Once a player reaches this day, their streak will be reset to 1 if it is true.

permissionRewards:
  loginstreak;special:
    weight: 0
    5:
      rewardType: ITEM
      reward: RED_WOOL;IRON_BLOCK
      commandExplanation: null
      commandScope: null
      rewardAmount: "30;10"
      weight: 1
    6:
      rewardType: COMMAND
      reward: "say %player% has donated to earn this special message on their 6th day of logging in!"
      commandExplanation: "announces that you have a 6 day streak and have a special permission node"
      commandScope: CONSOLE
      rewardAmount: "0"
  cool;permission;node:
    weight: 3
    5:
      rewardType: ITEM
      reward: IRON_BLOCK;DIAMOND_BLOCK
      commandExplanation: null
      commandScope: null
      rewardAmount: "45;15"
      weight: 2
    6:
      rewardType: COMMAND
      reward: "say %player% has logged in for 6 days and has the coolest permission node!;say This is from %player% as they have a special permission."
      commandExplanation: "announces that you have a 6 day streak and have a cool permission node"
      commandScope: CONSOLE;PLAYER
      rewardAmount: "0"