name: LoginStreak
version: ${project.version}
main: me.munch42.loginstreak.Main
api-version: 1.13

softdepend: [PlaceholderAPI]
depend: [Vault]

commands:
  streak:
    description: This command shows your current login streak.